dist: trusty
sudo: false
language: go

go:
  - 1.14.x

env:
  - TRAVIS_NODE_VERSION="10.13.0" GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.28.0

before_script:
  - export DISPLAY=:99.0
  - export NODE_OPTIONS=--max_old_space_size=4096
  - sh -e /etc/init.d/xvfb start

script: make build

notifications:
  slack: reportportal-dev:fl6xWHVQp1jvsMmCJxYW9YKP

after_success:
  - npm install -g codecov
  - codecov
